# * Set name of your application
application: Awesome

# * Username/password for HTTP Auth
username: ~
password: ~

# * Full path to your application, eg. "/var/www/my_rails_app"
path:  ~

# * Git remote (defaults to `origin` if not set)
git_remote: ~

# * Git branch (defaults to `master` if not set)
git_branch: ~

# * Setup notifications (http://github.com/karmi/pushr_notifiers)
# notifiers_path: "../somewhere/else" # Set this if your notifiers are not in ../pushr_notifiers
notifiers:
  # You'll probably want to protect the updates for this Twitter account :)
  - twitter:
     username: ~
     password: ~
  # For IRC see http://github.com/karmi/pushr_notifiers/blob/master/irc.rb
  # - irc:
  #      uri: 'irc://irc.freenode.net:6667/test'
  # For XMPP see http://github.com/karmi/pushr_notifiers/blob/master/jabber.rb
  # - jabber:
  #      username: ~
  #      password: ~
